name: SimpleCI/CDPipeline

# Define the trigger for the pipeline (e.g., push to the main branch)
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Your build commands go here
          # For example:
          # npm install
          # npm run build

      - name: Run Tests
        run: |
          # Your test commands go here
          # For example:
          # npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the 'build' job is completed before deploying

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          # Your deployment commands go here
          # For example:
          # Deploy the application to a production server

